import './App.css';
import { IoMdArrowForward } from "react-icons/io";
import { BiUndo } from "react-icons/bi";
import { AiOutlineRedo } from "react-icons/ai";
import React, { useState } from 'react';

function App() {
  const [genre, setGenre] = useState('');
  const [tone, setTone] = useState('');
  const [theme, setTheme] = useState('');
  const [prompt, setPrompt] = useState('');
  const [story, setStory] = useState('');

  return (
    <div className="App">

      <div className="header">
        <h1>Infinite Story Generator</h1>
        <button id="new-story">New Story</button>
      </div>

      <div className="dropdowns">
        <select value={genre} onChange={(e) => setGenre(e.target.value)}>
          <option value="" disabled hidden>Genre</option>
          <option value="fantasy">Fantasy</option>
          <option value="sci-fi">Sci-Fi</option>
          <option value="mystery">Mystery</option>
          <option value="romance">Romance</option>
          <option value="horror">Horror</option>
        </select>

        <select value={tone} onChange={(e) => setTone(e.target.value)}>
          <option value="" disabled hidden>Tone</option>
          <option value="lighthearted">Lighthearted</option>
          <option value="serious">Serious</option>
          <option value="dark">Dark</option>
          <option value="humorous">Humorous</option>
        </select>

        <select value={theme} onChange={(e) => setTheme(e.target.value)}>
          <option value="" disabled hidden>Theme</option>
          <option value="friendship">Friendship</option>
          <option value="adventure">Adventure</option>
          <option value="revenge">Revenge</option>
          <option value="coming-of-age">Coming of Age</option>
          <option value="survival">Survival</option>
        </select>
      </div>

      <div className="image">
        <p>(Image generated by DALL-E)</p>
      </div>

      <div className="story">
        <p>{story || "(Text generated by GPT)"}</p>
      </div>
      
      <textarea
        placeholder="Type your next prompt here..."
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
      ></textarea>


      <div className="buttons">
        <button onClick={async () => {
          try {
            const response = await fetch("http://localhost:5000/story", {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
              },
              body: JSON.stringify({ prompt }), // can add genre/tone/theme later
            });

            const data = await response.json();
            if (data.story) {
              setStory(data.story);
            } else {
              console.error("No story returned:", data);
            }
          } catch (error) {
            console.error("Error fetching story:", error);
          }
        }}>
          Continue <IoMdArrowForward />
        </button>

        <button>Undo <BiUndo /></button>
        <button>Regenerate <AiOutlineRedo /></button>
      </div>

      <footer>© 2025 Infinite Story Generator. Created by Vincent Le & Elena Parapounsky.</footer>
    </div>
  );
}

export default App;
