import './App.css';
import { IoMdArrowForward } from "react-icons/io";
import { BiUndo } from "react-icons/bi";
import { AiOutlineRedo } from "react-icons/ai";

function App() {
  return (
    <div className="App">

      <div className="header">
        <h1>Infinite Story Generator</h1>
        <button id="new-story">New Story</button>
      </div>

      <div className="dropdowns">
        <select>
          <option value="">Genre</option>
        </select>

        <select>
          <option value="">Tone</option>
        </select>

        <select>
          <option value="">Theme</option>
        </select>
      </div>

      <div className="image">
        <p>(Image generated by DALL-E)</p>
      </div>

      <div className="story">
        <p>(Text generated by GPT)</p>
      </div>
      
      <textarea placeholder="Type your next prompt here..."></textarea>

      <div className="buttons">
        <button>Continue <IoMdArrowForward /> </button>
        <button>Undo <BiUndo /> </button>
        <button>Regenerate <AiOutlineRedo /> </button>
      </div>

      <footer>© 2025 Infinite Story Generator. Created by Vincent Le & Elena Parapounsky.</footer>
    </div>
  );
}

export default App;
